"use client";
import { useEffect, useMemo, useState } from "react";
import { Box, Check, input } from "../FormControls";
const DATA_PATH="/data/SanMar_SDL_hue.csv"; const QUICK_STYLES=[{code:"2000",label:"Gildan Tee 2000"},{code:"G2400",label:"Gildan Long Sleeve G2400"},{code:"BC3001",label:"Bella Tee BC3001"},{code:"996M",label:"Jerzees Tee 996M"},{code:"1717",label:"Comfort Colors 1717"},{code:"ST350",label:"Sport-Tek ST350"},{code:"ST350LS",label:"Sport-Tek LS ST350LS"}]; const SIZES=["XS","S","M","L","XL","2XL","3XL","4XL","5XL","6XL"]; const QTY_TIERS=[24,50,100,150,200,250,300];
const SINGLE_SIDE={24:{1:6.5,2:7,3:7.5,4:8},50:{1:5.85,2:6.3,3:6.75,4:7.2},100:{1:5.53,2:5.95,3:6.38,4:6.8},150:{1:5.2,2:5.6,3:6,4:6.4},200:{1:4.88,2:5.25,3:5.63,4:6},250:{1:4.55,2:4.9,3:5.25,4:5.6},300:{1:4.23,2:4.55,3:4.88,4:5.2}};
const ADD_SIDE={24:{1:2,2:2.5,3:3,4:3.5},50:{1:1.8,2:2.25,3:2.7,4:3.15},100:{1:1.7,2:2.13,3:2.55,4:2.98},150:{1:1.6,2:2,3:2.4,4:2.8},200:{1:1.5,2:1.88,3:2.25,4:2.63},250:{1:1.4,2:1.75,3:2.1,4:2.45},300:{1:1.3,2:1.63,3:1.95,4:2.28}};
const n=(v)=>Number.parseFloat(String(v??"").replace(/[^0-9.-]/g,""))||0; const tier=(q)=>QTY_TIERS.reduce((a,t)=>q>=t?t:a,QTY_TIERS[0]); const zeroQty=()=>Object.fromEntries(SIZES.map((s)=>[s,"0"])); const item=(id)=>({id,search:"",styleKey:"",color:"",sizeQty:zeroQty(),open:false});
export default function ScreenPrinting({margin=60,multiplier=1,onSummaryChange}){const [rows,setRows]=useState([]); const [lineItems,setLineItems]=useState([item(1)]); const [locations,setLocations]=useState([{id:1,name:"Front",colors:1}]); const [setupFeeEnabled,setSetupFeeEnabled]=useState(false);
useEffect(()=>{fetch(DATA_PATH).then((r)=>r.text()).then((txt)=>{const [h,...lines]=txt.split(/\r?\n/).filter(Boolean);const cols=h.split(",");const i=Object.fromEntries(cols.map((k,ix)=>[k.trim(),ix]));setRows(lines.map((line)=>{const c=line.split(",");return{style:c[i["STYLE#"]],title:c[i.PRODUCT_TITLE],color:c[i.COLOR_NAME],size:c[i.SIZE],casePrice:n(c[i.CASE_PRICE])};}));}).catch(()=>setRows([]));},[]);
const styles=useMemo(()=>{const m=new Map();rows.forEach((r)=>{const k=`${r.style}__${r.title}`; if(!m.has(k))m.set(k,{key:k,style:r.style,title:r.title,rows:[]}); m.get(k).rows.push(r);}); return m;},[rows]);
const setLI=(id,u)=>setLineItems((p)=>p.map((x)=>x.id===id?u(x):x));
const pick=(id,key)=>{const g=styles.get(key);setLI(id,(x)=>({...x,styleKey:key,search:g?`${g.style} — ${g.title}`:"",open:false,color:x.color&&g?.rows.find((r)=>r.color===x.color)?x.color:""}));};
const quick=(id,style)=>{const g=[...styles.values()].find((s)=>s.style.toLowerCase()===style.toLowerCase()); if(!g)return; const colors=[...new Set(g.rows.map((r)=>r.color).filter(Boolean))]; const black=colors.find((c)=>c.toLowerCase()==="black")||colors.find((c)=>c.toLowerCase().includes("black"))||colors[0]||""; const q=zeroQty(); q.L="24"; setLI(id,(x)=>({...x,styleKey:g.key,search:`${g.style} — ${g.title}`,open:false,color:black,sizeQty:q}));};
const summary=useMemo(()=>{const PRODUCT_MARKUP_MULTIPLIER=1.15, PRODUCT_MARKUP_PERCENT=115; const li=lineItems.map((l)=>{const g=styles.get(l.styleKey); const t=Object.values(l.sizeQty).reduce((s,q)=>s+n(q),0); const matchedRows=(g?.rows||[]).filter((r)=>r.color===l.color); const garmentCost=SIZES.reduce((s,sz)=>{const q=n(l.sizeQty[sz]); const row=matchedRows.find((r)=>String(r.size).trim().toUpperCase()===sz); return s+(row?.casePrice||0)*q;},0); const casePrice=t?garmentCost/t:0; const markedUpGarmentPrice=casePrice*PRODUCT_MARKUP_MULTIPLIER; const garmentRetail=garmentCost*PRODUCT_MARKUP_MULTIPLIER; return {...l,style:g?.style||"",title:g?.title||"",totalQty:t,garmentCost,garmentRetail,casePrice,markedUpGarmentPrice,productMarkupPercent:PRODUCT_MARKUP_PERCENT};});
const totalGarments=li.reduce((s,x)=>s+x.totalQty,0), apparelDirectCost=li.reduce((s,x)=>s+x.garmentCost,0), apparelRetailSubtotal=li.reduce((s,x)=>s+x.garmentRetail,0); const t=tier(totalGarments);
const printLines=locations.map((loc,idx)=>{const per=((idx===0?SINGLE_SIDE:ADD_SIDE)[t]?.[loc.colors]||0); return {...loc,pricingType:idx===0?"First Side":"Additional Side",pricePerPrint:per,subtotal:per*totalGarments};});
const printChargePerShirt=printLines.reduce((s,x)=>s+x.pricePerPrint,0); const printChargeSubtotal=printLines.reduce((s,x)=>s+x.subtotal,0), setupFee=setupFeeEnabled?25:0, retail=apparelRetailSubtotal+printChargeSubtotal+setupFee, cost=apparelDirectCost;
const lineItemsWithAlloc=li.map((x)=>{const finalPerShirt=x.markedUpGarmentPrice+printChargePerShirt; const finalRetail=x.totalQty*finalPerShirt; return {...x,printChargeAllocated:x.totalQty*printChargePerShirt,setupFeeAllocated:0,finalRetailSubtotal:finalRetail,retailPerShirt:finalPerShirt,printChargePerShirt};});
return {retail,each:totalGarments?retail/totalGarments:0,cost,profit:retail-cost,margin:retail?((retail-cost)/retail)*100:0,materialCost:apparelDirectCost,shipping:0,totalGarments,apparelDirectCost,apparelRetailSubtotal,printChargeSubtotal,setupFee,lineItems:lineItemsWithAlloc,printLines,averagePricePerShirt:totalGarments?(apparelRetailSubtotal+printChargeSubtotal)/totalGarments:0,productMarkupPercent:115};
},[lineItems,styles,locations,setupFeeEnabled]); useEffect(()=>onSummaryChange?.(summary),[summary,onSummaryChange]);
return <Box title="Screen Printing (Beta)">{lineItems.map((li)=>{const g=styles.get(li.styleKey); const matches=li.search? [...styles.values()].filter((s)=>`${s.style} ${s.title}`.toLowerCase().includes(li.search.toLowerCase())).slice(0,25):[]; const colors=g?[...new Set(g.rows.map((r)=>r.color).filter(Boolean))]:[]; const det=summary.lineItems.find((x)=>x.id===li.id);
return <div key={li.id} style={{border:"1px solid #334155",padding:12,borderRadius:10,marginBottom:10,overflow:"hidden"}}><div className="buttonGrid" style={{marginBottom:8}}>{QUICK_STYLES.map((opt)=><button key={`${li.id}-${opt.code}`} className={`presetBtn ${g?.style===opt.code?"activePreset":""}`} onClick={()=>quick(li.id,opt.code)}>{opt.label}</button>)}</div>
<input style={input} placeholder="Search style # or product" value={li.search} onFocus={()=>setLI(li.id,(x)=>({...x,open:true}))} onChange={(e)=>setLI(li.id,(x)=>({...x,search:e.target.value,open:true,styleKey:""}))} />
{li.open&&matches.length>0&&<div style={{border:"1px solid #475569",borderRadius:8,maxHeight:180,overflowY:"auto",marginBottom:8}}>{matches.map((m)=><button key={m.key} className="modeBtn" style={{display:"block",width:"100%",textAlign:"left",margin:0,borderRadius:0,padding:"10px 12px"}} onClick={()=>pick(li.id,m.key)}>{m.style} — {m.title}</button>)}</div>}
<p style={{margin:"6px 0"}}><strong>Selected:</strong> {g?`${g.style} — ${g.title}`:"None"}</p>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12,width:"100%"}}><div><select style={input} value={li.color} onChange={(e)=>setLI(li.id,(x)=>({...x,color:e.target.value}))}><option value="">Select color</option>{colors.map((c)=><option key={c} value={c}>{c}</option>)}</select></div><div style={{display:"grid",gridTemplateColumns:"repeat(5,minmax(0,1fr))",gap:6,width:"100%"}}>{SIZES.map((s)=><label key={s} style={{fontSize:12}}>{s}<input style={{...input,marginTop:4,padding:"6px 8px",width:"100%",boxSizing:"border-box",minWidth:0}} value={li.sizeQty[s]} onChange={(e)=>setLI(li.id,(x)=>({...x,sizeQty:{...x.sizeQty,[s]:e.target.value.replace(/[^0-9]/g,"")}}))} onBlur={()=>setLI(li.id,(x)=>({...x,sizeQty:{...x.sizeQty,[s]:x.sizeQty[s]===""?"0":String(n(x.sizeQty[s]))}}))}/></label>)}</div></div>
<p>Total Qty: {det?.totalQty||0} • Garment Direct Cost: ${(det?.garmentCost||0).toFixed(2)} • Garment Retail Subtotal: ${(det?.garmentRetail||0).toFixed(2)}</p>{lineItems.length>1&&<button className="modeBtn" onClick={()=>setLineItems((p)=>p.filter((x)=>x.id!==li.id))}>Remove line item</button>}</div>;})}
<button className="modeBtn" style={{width:"100%",marginBottom:8}} onClick={()=>setLineItems((p)=>[...p,item(Date.now())])}>+ Add apparel line item</button><hr/><h4>Imprint Locations</h4>
{locations.map((loc,idx)=><div key={loc.id} style={{display:"grid",gridTemplateColumns:"2fr 1fr auto",gap:8,marginBottom:8}}><select style={input} value={loc.name} onChange={(e)=>setLocations((p)=>p.map((x)=>x.id===loc.id?{...x,name:e.target.value}:x))}><option>Front</option><option>Back</option><option>Left Sleeve</option><option>Right Sleeve</option></select><select style={input} value={loc.colors} onChange={(e)=>setLocations((p)=>p.map((x)=>x.id===loc.id?{...x,colors:n(e.target.value)}:x))}><option value={1}>1</option><option value={2}>2</option><option value={3}>3</option><option value={4}>4</option></select>{locations.length>1?<button className="modeBtn" onClick={()=>setLocations((p)=>p.filter((x)=>x.id!==loc.id))}>Remove</button>:<div/>}<div style={{gridColumn:"1 / -1",fontSize:12,opacity:.8}}>{idx===0?"First location uses single-sided matrix":"Additional location uses additional-side matrix"}</div></div>)}
<button className="modeBtn" style={{width:"100%"}} onClick={()=>setLocations((p)=>[...p,{id:Date.now(),name:"Back",colors:1}])}>+ Add print location</button><Check label="Artwork/Setup Fee (+$25)" value={setupFeeEnabled} setValue={setSetupFeeEnabled}/></Box>;
}
